# WereWolfPlugin Main Configuration

# Author Ph1Lou

# Link : https://www.spigotmc.org/resources/loup-garou-uhc.73113/

# Version 1.9

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2020-2021
# Available (en_EN, fr_FR)

lang: fr_FR
default_lobby: true
server_uuid:

